spring.application.name=demo

server.port=${PORT:8082}

spring.mvc.servlet.path=/api

# Database Ba?lant?s?
spring.datasource.url=jdbc:postgresql://dpg-d9vem5m417fc73crcfn0-a/demo_db_1zsu
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA v? Hibernate T?nziml?m?l?ri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect