spring.application.name=demo

server.port=${PORT:8082}

spring.mvc.servlet.path=/api

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false